include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    invalid_annotation_target: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/apis/**/handler/**"

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    prefer_const_constructors: false
    prefer_initializing_formals: false
    depend_on_referenced_packages: false